# LDAP compatibility example. Export IMPALA_USERNAME and IMPALA_PASSWORD.
connection.auth.mode = LDAP
connection.url = jdbc:impala://impala.example.com:21050/default;AuthMech=3;SSL=1
jdbc.driver.class.name = com.cloudera.impala.jdbc41.Driver
connection.query = SELECT CURRENT_USER()
