# OAuth 2.0 token pass-through example. Export IMPALA_OAUTH_ACCESS_TOKEN.
connection.auth.mode = OAUTH_TOKEN
connection.url = jdbc:impala://impala.example.com:28000/default;AuthMech=11;Auth_Flow=0;SSL=1;TransportMode=http;httpPath=cliservice
jdbc.driver.class.name = com.cloudera.impala.jdbc41.Driver
connection.query = SELECT CURRENT_USER()
